# MeshFleet Benchmark Configuration File
# This file configures the evaluation pipeline for 3D model quality assessment

# File paths configuration
paths:
  ground_truth_folder: "data/meshfleet/benchmark_data/meshfleet_eval_images"
  # generated_folder: "data/meshfleet/generated"
  generated_folder: "/mnt/damian/Projects/TRELLIS/prompt_alignment_images_testset/generated_flux_lora_maxR"
  output_folder: "data/meshfleet_evaluation"
  metadata_file: "data/meshfleet/meshfleet_test.csv"
  metrics_config: "meshfleet_benchmark/config_meshfleet.json"

# Preprocessing configuration
preprocessing:
  background_removal:
    enabled: true # Whether to remove backgrounds from images, will replace the original images
    single_thread: false  # Set to true for single-threaded processing
  
  view_alignment:
    enabled: true # Whether to align views of the 3D models with the ground truth
  
  scale_equalization:
    enabled: true
    force: false
    canvas_size: [768, 768]  # Canvas size for scaling
    fill_ratio: 0.9  # How much of the canvas to fill

# Evaluation configuration
evaluation:
  semantic_geometric:
    enabled: true
  
  prompt_following:
    enabled: true
  
  vehicle_dimensions:
    enabled: true
  
  filter_by_metadata:
    enabled: true  # Whether to filter objects using metadata file

# Runtime configuration
runtime:
  device: "auto"  # Options: "auto", "cuda", "cpu"
  omp_num_threads: "1"  # Number of OpenMP threads
